# Generated by Django 3.0.1 on 2019-12-29 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WritingContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='최대 200자 입력가능', max_length=200)),
                ('contents', models.TextField()),
                ('timeSet', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('score', models.CharField(choices=[('first', 'star score 1'), ('second', 'star score 2'), ('third', 'star score 3'), ('fourth', 'star score 4'), ('fifth', 'star score 5')], max_length=100)),
            ],
        ),
    ]
